### PR TITLE
feat(deploy & utils): add support for bitbucket pipeline

### PR DESCRIPTION
**Pull request by kde713**
### Description

- **Major** Added support for bitbucket pipeline
- **Minor** Seperate some ci related method to `utils/ci.js`
    + Now `utils/ci.js` has `getBranch`, `isPullRequest`, `getCommitMessage` methods

### Check List

- [x] All test passed
- [x] Added test to ensure to fix/ensure properly.
    + No Additional Test Required for this PR

### CODE REVIEW

**Comment by prescottprue** [comment]
Nice work! Love the detailed PR and moving of the utils.

I'm going to point this to this PR to a version branch then merge that into `next`. There are some other features, including support for Gitlab, that are also on that tag.

**Comment by prescottprue** [comment]
Oh, it seems like you actually did some very similar changes. Though I called it `getDeployMessage` and you called it `getCommitMessage`, we made a function for the exact same thing 😆 .

I am going to just go ahead and merge yours to master. Since it doesn't have a version bump, it won't go out to npm right away, but I will then deal with merge conflicts between `next` - master. 

Thanks again!

**Comment by prescottprue** [comment]
Here is [the PR for v0.5.0-alpha.4](https://github.com/prescottprue/firebase-ci/pull/27) which includes the changes. It is late here, so I will try to get to the merging after some sleep 😄

**Comment by kde713** [comment]
@precottprue Thanks for approval!! I love ur project :)

**Pull request merged**
